### ISSUE TITLE
Quest progress reset after maintenance for RDM AF3 - Peace for the Spirit

### ISSUE THREAD

**Issue by dolomedes03** [HorizonFFXI/HorizonXI-Issues#1177]
Last night, between 1-5AM EST, I worked with a group to complete the RDM AF3 quest.  We killed Miser Murphy, I traded my coin to the fountain.  We went to Garlaige, killed Guardian Statue, got the nail puller and I traded it to the box and got the cutscene.  I logged off there.  Today, after maintenance, I logged in and went to North Sandy for the cutscene which didn't trigger.  I went to the NPC in Lion's Spring and he's telling me to go do the Fei Yin step with the antique coin.  Why is it starting me over?  Did today's maintenace on that quest completely reset my progress?

Please don't tell me I have to do all that again.  It took 4 hours.

I'm trying to remember all the people in my party.   Some will likely have similar issues.  Coraic, Tox, Mystiq, Lilia(something), Aedirn  (I'm misspelling this one, can't remember exactly)

**Comment by The-Aerec** [comment]
I have pushed a fix for this, please let me know if it works. @dolomedes03

**Comment by dolomedes03** [comment]
No, still no cutscene for zoning in to North Sandoria.  I zoned in first via warp, then went to W. Ronfaure and back, then to S. Sandy and back.  No cutscene.  My concern now is because I went back to the NPC in Lion Springs it's reset my quest progress to earlier in the quest so I'm no longer eligible to complete it.

**Comment by dolomedes03** [comment]
I just spoke with Coraic, Aedrinn and Liliaflonne.   Coraic picked up his chapeau before logging last night, he's fine.  Liliaflonne and Aedrinn are in the same boat as me where the cutscene won't trigger because they logged off before turning it in/maintenance.

**Comment by Fr0zt** [comment]
This is Aedrinn, I'm still not able to get the cutscene. I have zoned into northern sandoria from every entrance and cant get the scene.

**Comment by Liliaflonne** [comment]
I have the nail puller from the guardian statue but couldnt re clear the room before maintenance to trigger the cutscene in garliage citadel, zoned and tried, relogged and tried, the dialogue from the oaken box asks me to trade the nail puller but nothing happens, been through northern sandoria many times since to prove my progress is still stuck at the oaken box part of the quest

**Comment by Fr0zt** [comment]
Should we open a GM ticket for this to get our hat since we can't finish the quest anymore and can't receive the reward due to quest progess being broken from an update?

**Comment by dolomedes03** [comment]
I don't know what to do.  There was the quick answer yesterday positing there was a fix but that obviously didn't take and now it's radio silence.

**Comment by Liliaflonne** [comment]
if it requires a full quest reset for whatever reason, do you want to group up to do it again and just not on a friday? xD

**Comment by Fr0zt** [comment]
I don't see why we would be required to waste another 3 hours doing a quest we have already done to receive an item we already earned because they broke the quest in a patch. An update on the situation would be nice, or let us know if we should open a GM ticket to receive the item instead.

**Comment by Fr0zt** [comment]
The patch reset our quest progress, I just talked to Sharzalion and he tells me to get an antique coin again...

**Comment by Liliaflonne** [comment]
I redid the quest and managed to get mine

**Comment by dolomedes03** [comment]
@The-Aerec  Any update on this, even to just set an expectation?  Can or will this be remedied administratively or tough luck we need to redo the quest?  If it can be resolved administratively, when?  Days?  Weeks?  This would help inform a gameplay decision on whether or not to suck it up and do it again.  I appreciate this is likely a small potatoes issue compared to other bugs but it's important to those of us that invested the time to do it only to have it undone by things out of our control.

**Comment by hammicus** [comment]
@Fr0zt - the same thing happened to me.  Sharazlion asks me to get the antique coin again.  @The-Aerec  are we expected do do the whole quest again?
